#!/usr/bin/env python3
"""Generate static native hook emitters; no generator runs in installed hooks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def surfaces(root: Path) -> dict[str, str]:
    context = (root / "hooks/primer.txt").read_text(encoding="utf-8").strip()
    # Literal CMD/PowerShell/shell output must not turn primer text into code.
    if (
        not context
        or len(context) > 512
        or any(c in context for c in "\n\r'\"<>%&|^!`$\\")
    ):
        raise ValueError(
            "primer must be a single safe literal of at most 512 characters"
        )
    payloads = {
        "session-start": {
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": context,
            }
        },
        "cursor-session-start": {"additional_context": context},
        "agy-pre-invocation": {"injectSteps": [{"ephemeralMessage": context}]},
    }
    result = {}
    for stem, payload in payloads.items():
        encoded = json.dumps(payload, separators=(",", ":"))
        result[f"hooks/{stem}.sh"] = (
            "#!/usr/bin/env bash\n# Generated by tools/sync-hook-surfaces.py.\n"
            f"set -eu\n\nprintf '%s\\n' '{encoded}'\n"
        )
        if stem != "cursor-session-start":
            result[f"hooks/{stem}.ps1"] = (
                "# Generated by tools/sync-hook-surfaces.py.\n"
                f"[Console]::Out.WriteLine('{encoded}')\n"
            )
        if stem == "session-start":
            result[f"hooks/{stem}.cmd"] = (
                "@echo off\nREM Generated by tools/sync-hook-surfaces.py.\n"
                f"echo {encoded}\n"
            )
            result[f"hooks/{stem}.js"] = (
                "// Generated by tools/sync-hook-surfaces.py.\n"
                f"process.stdout.write({json.dumps(encoded + chr(10))});\n"
            )
    result[".codex/hooks.json"] = (root / "hooks/hooks-codex.json").read_text(
        encoding="utf-8"
    )
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    args = parser.parse_args()
    stale = []
    for name, content in surfaces(args.repo_root).items():
        path = args.repo_root / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            if path.suffix == ".sh":
                path.chmod(0o755)
    if stale:
        print("Stale hook surfaces: " + ", ".join(stale))
        print("Run make sync-hook-surfaces")
        return 1
    print("Hook surfaces are current." if args.check else "Hook surfaces generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
